config/routes.rb
Rails.application.routes.draw do
  resources :subsrcibingplans
  resources :schooldetails
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/schooldetail.rb
class Schooldetail < ApplicationRecord
	# validates :schoolname, presence: true, format: { with: /\A[a-zA-Z]+\z/,
 #    message: "only allows letters" }
 #     validates :address, presence: true,confirmation: { case_sensitive: false }
 #     validates :city, presence: true
 #     validates :state, presence: true
 #     validates :pincode, presence: true
 #     validates :affiliatedboard, presence: true

end

app/models/subsrcibingplan.rb
class Subsrcibingplan < ApplicationRecord
     # validates :subject, presence: true 
  
	before_save do 
		self.features.gsub!(/[\[\]\"]/,"") if attribute_present?("features")
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/schooldetails_controller.rb
class SchooldetailsController < ApplicationController
  before_action :set_schooldetail, only: [:show, :edit, :update, :destroy]

  # GET /schooldetails
  # GET /schooldetails.json
  def index
    @schooldetails = Schooldetail.all
  end

  # GET /schooldetails/1
  # GET /schooldetails/1.json
  def show
  end

  # GET /schooldetails/new
  def new
    @schooldetail = Schooldetail.new
  end

  # GET /schooldetails/1/edit
  def edit
  end

  # POST /schooldetails
  # POST /schooldetails.json
  def create
    @schooldetail = Schooldetail.new(schooldetail_params)

    respond_to do |format|
      if @schooldetail.save
        format.html { redirect_to @schooldetail, notice: 'Schooldetail was successfully created.' }
        format.json { render :show, status: :created, location: @schooldetail }
      else
        format.html { render :new }
        format.json { render json: @schooldetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schooldetails/1
  # PATCH/PUT /schooldetails/1.json
  def update
    respond_to do |format|
      if @schooldetail.update(schooldetail_params)
        format.html { redirect_to @schooldetail, notice: 'Schooldetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @schooldetail }
      else
        format.html { render :edit }
        format.json { render json: @schooldetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schooldetails/1
  # DELETE /schooldetails/1.json
  def destroy
    @schooldetail.destroy
    respond_to do |format|
      format.html { redirect_to schooldetails_url, notice: 'Schooldetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schooldetail
      @schooldetail = Schooldetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schooldetail_params
      params.require(:schooldetail).permit(:schoolname, :address, :city, :state, :pincode, :affiliatedboard)
    end
end

app/controllers/subsrcibingplans_controller.rb
class SubsrcibingplansController < ApplicationController
  before_action :set_subsrcibingplan, only: [:show, :edit, :update, :destroy]

  # GET /subsrcibingplans
  # GET /subsrcibingplans.json
  def index
    @subsrcibingplans = Subsrcibingplan.all
  end

  # GET /subsrcibingplans/1
  # GET /subsrcibingplans/1.json
  def show
  end

  # GET /subsrcibingplans/new
  def new
    @subsrcibingplan = Subsrcibingplan.new
  end

  # GET /subsrcibingplans/1/edit
  def edit
  end

  # POST /subsrcibingplans
  # POST /subsrcibingplans.json
  def create
    @subsrcibingplan = Subsrcibingplan.new(subsrcibingplan_params)

    respond_to do |format|
      if @subsrcibingplan.save
        format.html { redirect_to @subsrcibingplan, notice: 'Subsrcibingplan was successfully created.' }
        format.json { render :show, status: :created, location: @subsrcibingplan }
      else
        format.html { render :new }
        format.json { render json: @subsrcibingplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subsrcibingplans/1
  # PATCH/PUT /subsrcibingplans/1.json
  def update
    respond_to do |format|
      if @subsrcibingplan.update(subsrcibingplan_params)
        format.html { redirect_to @subsrcibingplan, notice: 'Subsrcibingplan was successfully updated.' }
        format.json { render :show, status: :ok, location: @subsrcibingplan }
      else
        format.html { render :edit }
        format.json { render json: @subsrcibingplan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subsrcibingplans/1
  # DELETE /subsrcibingplans/1.json
  def destroy
    @subsrcibingplan.destroy
    respond_to do |format|
      format.html { redirect_to subsrcibingplans_url, notice: 'Subsrcibingplan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subsrcibingplan
      @subsrcibingplan = Subsrcibingplan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subsrcibingplan_params
      params.require(:subsrcibingplan).permit(:subject, features:[])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schooldetails_helper.rb
module SchooldetailsHelper
end

app/helpers/subsrcibingplans_helper.rb
module SubsrcibingplansHelper
	def checked(area)
		@subsrcibingplan.features.nil? ? false : @subsrcibingplan.features.match(area)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schoolregisterform</title>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="container-fluid">
      <div class="logo-part">
        <img class="logo" alt="Brand" src="../assets/Skala-icon.png"> 
       <%= link_to image_tag("settings.svg",class:'a'), new_schooldetail_path, :method => :delete %>
        </div>
    </div>
  </header>
  <div class="navbar">
      <ul class="">
      <li><img alt="Brand" src="../assets/male3.svg"> <%= link_to 'User Management Portal', new_schooldetail_path %></li>
      <li><img alt="Brand" src="../assets/cash-register.svg"><%= link_to 'Registration Portal', new_schooldetail_path %></li>
      <li><img alt="Brand" src="../assets/controls.svg"> <%= link_to 'Content Portal', new_schooldetail_path %></li> 
    </ul>
  </div>
  <img  src="../assets/Cancel-128.png" ,>
    <%= yield %>
  </body>
</html>

app/views/schooldetails/_form.html.erb
<%= form_for(schooldetail) do |f| %>
  <% if schooldetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schooldetail.errors.count, "error") %> prohibited this schooldetail from being saved:</h2>

      <ul>
      <% schooldetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "form-container">
<div class= "form">
<h1 id= "newschooldetails">NEW SCHOOl DETAILS </h1>
<div class= "part1">
  <div class="field">
    <%= f.label :name, "SCHOOLNAME" ,id:"schoolname" %>
    <%= f.text_field :schoolname %></br>
  </div></br>

  <div class="schoola">
    <%= f.label :name, "ADDRESS",id:"schooladdress" %>
    <%= f.text_area :address %></br>
  </div></br>

  <div class="schoolcity">
    <%= f.label :name, "CITY"%></br>
    <%= f.text_field :city,class:"field" %></br>
  </div></br>

  <div class="schoolstate ">
    <%= f.label :name,"STATE"%></br>
    <%= f.text_field :state,class:"field" %>
  </div>

  <div class="schoolstate">
    <%= f.label :name, "PINCODE" %></br>
    <%= f.text_field :pincode,class:"field" %>
  </div>
  </div>
  
   <!-- <div class= "part2">
   <div class="radiobuttons">
    <%= f.label :name,"AFFILIATEDBOARD",class:"affiliatedboard" %></br>
    <%= f.radio_button :affiliatedboard,'CBSE' %><%=f.label :name,'ICSE',class:"radio" %>
    <%= f.radio_button :affiliatedboard,'ICSE' %><%=f.label :name,'ICSE',class:"radio" %>
    <%= f.radio_button :affiliatedboard, 'Matric'%><%=f.label :name,'Matric',class:"radio" %></br>
    <%= f.radio_button :affiliatedboard, 'StateBoard'%><%=f.label :name,'StateBoard',class:"stateboard" %>

  </div> 
  </div> -->
    <div class="left-part">
  <%= f.label :name ,"AFFILIATED BOARD:", class:"text-muted" %><br/>
    <div class="field">
      <%= f.radio_button :affiliatedboard, 'CBSE'%><%= f.label :name," CBSE" ,class:"text" %>
      <%= f.radio_button :affiliatedboard, 'ICSE' %><%= f.label :name," ICSE" ,class:"text" %>
      <%= f.radio_button :affiliatedboard, 'MATRIC' %><%= f.label :name," MATRIC" ,class:"text" %> <br/>
      <%= f.radio_button :affiliatedboard, 'STATE BOARD' %><%= f.label :name," STATE BOARD" ,class:"text" %> <br/>
    </div>
  </div> 
<!-- </div> -->

   
    
   
 
  <div class="actions">
    <%= f.submit "SchoolDetailSubmit" ,class:"Submit" %>
  </div>
  </div>
  </div>
<% end %>

app/views/schooldetails/edit.html.erb
<h1>Editing Schooldetail</h1>

<%= render 'form', schooldetail: @schooldetail %>

<%= link_to 'Show', @schooldetail %> |
<%= link_to 'Back', schooldetails_path %>

app/views/schooldetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schooldetails</h1>

<table>
  <thead>
    <tr>
      <th>Schoolname</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Pincode</th>
      <th>Affiliatedboard</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schooldetails.each do |schooldetail| %>
      <tr>
        <td><%= schooldetail.schoolname %></td>
        <td><%= schooldetail.address %></td>
        <td><%= schooldetail.city %></td>
        <td><%= schooldetail.state %></td>
        <td><%= schooldetail.pincode %></td>
        <td><%= schooldetail.affiliatedboard %></td>
        <td><%= link_to 'Show', schooldetail %></td>
        <td><%= link_to 'Edit', edit_schooldetail_path(schooldetail) %></td>
        <td><%= link_to 'Destroy', schooldetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schooldetail', new_schooldetail_path %>

app/views/schooldetails/new.html.erb
<%= render 'form', schooldetail: @schooldetail %>

app/views/schooldetails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Schoolname:</strong>
  <%= @schooldetail.schoolname %>
</p>

<p>
  <strong>Address:</strong>
  <%= @schooldetail.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @schooldetail.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @schooldetail.state %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @schooldetail.pincode %>
</p>

<p>
  <strong>Affiliatedboard:</strong>
  <%= @schooldetail.affiliatedboard %>
</p>

<%= link_to 'Edit', edit_schooldetail_path(@schooldetail) %> |
<%= link_to 'Back', schooldetails_path %>

app/views/subsrcibingplans/_form.html.erb
<%= form_for(subsrcibingplan) do |f| %>
  <% if subsrcibingplan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subsrcibingplan.errors.count, "error") %> prohibited this subsrcibingplan from being saved:</h2>

      <ul>
      <% subsrcibingplan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class= "subsrcibform">
  <h1>New Subsrcibingplan</h1>
  <div class="subject-container">
   <%= f.label :name ,"SUBJECT",class:"subject" %>
    
    <%= f.radio_button :subject, 'ALL' %><%= f.label :name,"ALL" ,class:"subject-radio" %>
    <%= f.radio_button :subject, 'ICT ONLY' %><%= f.label :name,"ICT ONLY" ,class:"subject-radio" %>
  </div>

  <div class="features-container">
    <%= f.label :name ,"FEATURES(select at applicable)",class:"subject" %><br>
        <div class = "ck-button-pa">
           

           <div id="ck-button-pa1">
              <label>
                <%= check_box_tag 'subsrcibingplan[features][]','BUZZLE',checked('BUZZLE'),id:"select"%><span >BUZZLE</span>
              </label>
           </div>
           <div id="ck-button-pa2">
               <label>
                 <%= check_box_tag 'subsrcibingplan[features][]','THINKMATE',checked('THINKMATE'),class: "select_all" %><span>THINKMATE</span>
               </label>
           </div>
        

        </div>  
     
     

     <div class = "ck-button-ch">
          

          <div id="ck-button-ch1">
               <label>
                   <%= check_box_tag 'subsrcibingplan[features][]','PPG',checked('PPG'),class:"checkbox" %><span>PPG</span>
              </label>
          </div>
          <div id="ck-button-ch2">
              <label>
                   <%= check_box_tag 'subsrcibingplan[features][]','QPG',checked('QPG'),class:"checkbox" %><span>QPG</span>
              </label>
          </div>
      <div class = "last"> 
              <div id="ck-button-ch3">

               <label>
                  <%= check_box_tag 'subsrcibingplan[features][]','Assessment',checked('Assessment'),class:"checkbox" %><span>Assessment</span>
              </label>
              </div>
          <div id="ck-button-ch4">
              <label>
                   <%= check_box_tag 'subsrcibingplan[features][]','Reports',checked('Reports'),class:"checkbox",id:"last" %><span>Reports</span>
               </label>
         </div> 
        </div>
     

     </div>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/subsrcibingplans/edit.html.erb
<h1>Editing Subsrcibingplan</h1>

<%= render 'form', subsrcibingplan: @subsrcibingplan %>

<%= link_to 'Show', @subsrcibingplan %> |
<%= link_to 'Back', subsrcibingplans_path %>

app/views/subsrcibingplans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subsrcibingplans</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Features</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subsrcibingplans.each do |subsrcibingplan| %>
      <tr>
        <td><%= subsrcibingplan.subject %></td>
        <td><%= subsrcibingplan.features %></td>
        <td><%= link_to 'Show', subsrcibingplan %></td>
        <td><%= link_to 'Edit', edit_subsrcibingplan_path(subsrcibingplan) %></td>
        <td><%= link_to 'Destroy', subsrcibingplan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subsrcibingplan', new_subsrcibingplan_path %>

app/views/subsrcibingplans/new.html.erb
<%= render 'form', subsrcibingplan: @subsrcibingplan %>

app/views/subsrcibingplans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @subsrcibingplan.subject %>
</p>

<p>
  <strong>Features:</strong>
  <%= @subsrcibingplan.features %>
</p>

<%= link_to 'Edit', edit_subsrcibingplan_path(@subsrcibingplan) %> |
<%= link_to 'Back', subsrcibingplans_path %>